seed: 0
data_dir: 'data'

simsiam:
  num_epoch: 300
  batch_size: 512
  lr: 0.06
  wd: 0.0005
  momentum: 0.9
  resize: 32
  warmup_epoch: 10
  warmup_lr: 0.
  final_lr: 0.
  tensorboard_dir: 'logs/train'
  model_dir: 'results/train'

linear:
  num_epoch: 100
  batch_size: 512
  lr: 30
  wd: 0
  momentum: 0.9
  warmup_epoch: 10
  warmup_lr: 0.
  final_lr: 0.
  tensorboard_dir: 'logs/eval'
  model_dir: 'results/eval'
  model_file: 'results/train/best_loss.pkl'
